import { useEffect, useRef, useState } from 'react';
import { createWidget } from '@layr0/chart-engine/widget';
import { ImcMarketDataFeed } from '../../services/imcFeeds';
import { completedBars, loadForecastCalendar, nextForecastTimes } from '../../services/forecastCalendar';
import { requestTimesFMForecast, requestTimesFMCalibrationStatusByRunId, startTimesFMCalibration } from '../../services/timesfmForecast';
import { forecastRequestKey, forecastRequestId } from '../../services/forecastIdentity';
import { AUTHORITATIVE_REFRESH_INTERVAL_MS } from '../../services/refreshPolicy';

const intervals = ['1m', '5m', '15m', '1h', '1d', '1w'];
const futureStyle = { title: 'TimesFM forecast', upColor: 'rgba(139, 92, 246, 0.72)', downColor: 'rgba(245, 158, 11, 0.72)', borderUpColor: '#a78bfa', borderDownColor: '#fbbf24', wickUpColor: '#a78bfa', wickDownColor: '#fbbf24', priceLineVisible: false, lastValueVisible: false };
const fulfilledStyle = { title: 'TimesFM fulfilled forecast', upColor: '#a78bfa', downColor: '#fbbf24', borderUpColor: '#a78bfa', borderDownColor: '#fbbf24', wickUpColor: '#a78bfa', wickDownColor: '#fbbf24', bodyVisible: false, priceLineVisible: false, lastValueVisible: false };
const quantileStyles = {
  P10: { color: 'rgba(129, 140, 248, 0.55)', lineWidth: 1, lineStyle: 'dashed', priceLineVisible: false, lastValueVisible: false },
  P25: { color: 'rgba(167, 139, 250, 0.65)', lineWidth: 1, lineStyle: 'dotted', priceLineVisible: false, lastValueVisible: false },
  P50: { color: '#c4b5fd', lineWidth: 2, priceLineVisible: false, lastValueVisible: false },
  P75: { color: 'rgba(251, 191, 36, 0.65)', lineWidth: 1, lineStyle: 'dotted', priceLineVisible: false, lastValueVisible: false },
  P90: { color: 'rgba(251, 191, 36, 0.55)', lineWidth: 1, lineStyle: 'dashed', priceLineVisible: false, lastValueVisible: false },
};
const quantileLegend = [
  ['P10', 'Lowest 10% outcome boundary', 'rgba(129, 140, 248, 0.9)', 'dashed'],
  ['P25', 'Lower-quarter outcome boundary', 'rgba(167, 139, 250, 0.95)', 'dotted'],
  ['P50', 'Median / central forecast', '#c4b5fd', 'solid'],
  ['P75', 'Upper-quarter outcome boundary', 'rgba(251, 191, 36, 0.95)', 'dotted'],
  ['P90', 'Highest 10% outcome boundary', 'rgba(251, 191, 36, 0.9)', 'dashed'],
];

export default function ChartTerminal({ client, active, onActiveChange, theme, forecastMode, forecastDiagnosticsVisible = true, forecastUncertaintyVisible = true, onForecastUncertaintyVisible }) {
  const host = useRef(null); const widget = useRef(null); const mode = useRef(forecastMode); const forecastAbort = useRef(null); const calibrationAbort = useRef(null); const forecastByTime = useRef(new Map()); const fulfilledByTime = useRef(new Map()); const generation = useRef(0); const transition = useRef(0); const lastRequestKey = useRef(''); const pendingHistoryKey = useRef(''); const calibrationContextKey = useRef(''); const calibrationRunId = useRef(''); const calibrationStatusRef = useRef('not-run'); const calibrationHistoryBars = useRef(0);
  const initial = useRef({ symbol: active.symbol, exchange: active.exchange, interval: active.interval, theme }); const callbacks = useRef({ client, onActiveChange });
  const [error, setError] = useState(''); const [forecast, setForecast] = useState({ status: 'Waiting for broker history', generatedAt: null, count: 0, uncertainty: null }); const uncertaintyVisible = useRef(forecastUncertaintyVisible); const quantileSeriesRef = useRef({}); const calibrationTimer = useRef(null);
  useEffect(() => { mode.current = forecastMode; }, [forecastMode]); useEffect(() => { uncertaintyVisible.current = forecastUncertaintyVisible; }, [forecastUncertaintyVisible]); useEffect(() => { callbacks.current = { client, onActiveChange }; }, [client, onActiveChange]);

  useEffect(() => { try {
    const feed = new ImcMarketDataFeed(callbacks.current.client);
    const createdWidget = createWidget(host.current, { feed, symbol: initial.current.symbol, exchange: initial.current.exchange, interval: initial.current.interval, intervals, theme: initial.current.theme, persist: false, mobile: 'auto', lookbackBars: 700, loading: { pollIntervalMs: AUTHORITATIVE_REFRESH_INTERVAL_MS }, symbolSearch: async (query) => { const result = await callbacks.current.client.search(query); return (result.data || result.symbols || []).map((item) => ({ symbol: item.symbol, exchange: item.exchange })); }, onOrder: () => document.querySelector('.trading-panel')?.scrollIntoView({ behavior: 'smooth' }) });
    widget.current = createdWidget;
    const futureSeries = createdWidget.chart.addSeries('candlestick', { style: futureStyle }); const fulfilledSeries = createdWidget.chart.addSeries('candlestick', { style: fulfilledStyle }); const quantileSeries = Object.fromEntries(Object.entries(quantileStyles).map(([name, style]) => [name, createdWidget.chart.addSeries('line', { style })])); quantileSeriesRef.current = quantileSeries;
    const setQuantileData = (uncertainty) => { const horizon = uncertainty?.horizon || []; const source = uncertainty?.display_source === 'calibrated' ? 'calibrated' : 'native'; const keys = ['P10', 'P25', 'P50', 'P75', 'P90']; keys.forEach((name) => quantileSeries[name].setData(uncertaintyVisible.current ? horizon.map((item) => ({ time: Number(item.timestamp), value: Number(item.quantiles?.[name] ?? item[name.toLowerCase()]) })) : [])); return source; };
    const clearForecast = (status = 'Waiting for broker history') => { forecastAbort.current?.abort(); forecastAbort.current = null; calibrationAbort.current?.abort(); calibrationAbort.current = null; if (calibrationTimer.current) clearInterval(calibrationTimer.current); calibrationTimer.current = null; calibrationContextKey.current = ''; calibrationRunId.current = ''; calibrationStatusRef.current = 'not-run'; calibrationHistoryBars.current = 0; pendingHistoryKey.current = ''; futureSeries.setData([]); fulfilledSeries.setData([]); Object.values(quantileSeries).forEach((series) => series.setData([])); forecastByTime.current.clear(); fulfilledByTime.current.clear(); lastRequestKey.current = ''; setForecast({ status, generatedAt: null, count: 0, uncertainty: null }); };
    const beginTransition = (interval) => { transition.current += 1; generation.current += 1; createdWidget.series.setData([]); clearForecast(`Loading ${interval} history`); };
    const runForecast = async ({ force = false } = {}) => {
      const transitionId = transition.current; const symbol = createdWidget.symbol(); const exchange = createdWidget.exchange(); const interval = createdWidget.interval(); const bars = completedBars(createdWidget.series.getData(), interval); if (bars.length === 0) { setForecast((previous) => ({ ...previous, status: `Loading ${interval} history` })); return; }
      for (const actual of bars) { const predicted = forecastByTime.current.get(actual.time); if (predicted) fulfilledByTime.current.set(actual.time, predicted); } if (mode.current === 'rolling-10') fulfilledByTime.current.clear();
      const history = bars.slice(-512).map(({ time, open, high, low, close, volume }) => ({ time, open, high, low, close, volume })); const pendingKey = JSON.stringify({ symbol, exchange, interval, history }); if (!force && pendingHistoryKey.current === pendingKey) return; pendingHistoryKey.current = pendingKey;
      setForecast((previous) => ({ ...previous, status: `Forecasting ${interval} with TimesFM…` })); setError('');
      let requestKey; const requestId = ++generation.current; const controller = new AbortController(); forecastAbort.current?.abort(); forecastAbort.current = controller;
      try {
        const calendar = await loadForecastCalendar(callbacks.current.client, history.at(-1).time, exchange, { signal: controller.signal }); if (controller.signal.aborted || transitionId !== transition.current || requestId !== generation.current) return;
        const futureTimestamps = nextForecastTimes({ lastTime: history.at(-1).time, interval, ...calendar }); requestKey = forecastRequestKey({ symbol, exchange, interval, bars: history, futureTimestamps }); const compactRequestId = forecastRequestId(requestKey); if (!force && lastRequestKey.current === requestKey && forecastByTime.current.size === 10) return;
        const result = await requestTimesFMForecast({ symbol, exchange, interval, bars: history, futureTimestamps, requestId: compactRequestId, calibrationContextKey: calibrationContextKey.current || undefined, signal: controller.signal }); if (requestId !== generation.current || transitionId !== transition.current || controller.signal.aborted || createdWidget.isDestroyed) return;
        const candles = result.candles.map((candle) => ({ time: Number(candle.time), open: Number(candle.open), high: Number(candle.high), low: Number(candle.low), close: Number(candle.close), volume: Number(candle.volume || 0) })); forecastByTime.current = new Map(candles.map((candle) => [candle.time, candle])); futureSeries.setData(candles); setQuantileData(result.uncertainty); fulfilledSeries.setData(mode.current === 'retain-fulfilled-overlays' ? [...fulfilledByTime.current.values()] : []); lastRequestKey.current = requestKey;
        const backendReady = result.uncertainty?.calibration_status === 'ready'; if (backendReady) { calibrationStatusRef.current = 'ready'; calibrationRunId.current = result.uncertainty.calibration_run_id || calibrationRunId.current; calibrationContextKey.current = result.uncertainty.calibration_context_key || calibrationContextKey.current; calibrationHistoryBars.current = Number(result.uncertainty.calibration_history_bars || calibrationHistoryBars.current || bars.length); }
        let calibrationState = bars.length < 106 ? { ...result.uncertainty, calibration_status: 'unavailable' } : { ...result.uncertainty, calibration_status: backendReady ? 'ready' : (calibrationStatusRef.current === 'running' ? 'running' : 'running'), calibration_run_id: calibrationRunId.current || undefined, calibration_context_key: calibrationContextKey.current || undefined };
        const publishForecast = (state) => { const calibrationStatus = state.calibration_status; const statusLabel = calibrationStatus === 'running' ? 'TimesFM 3 forecast — calibration running' : calibrationStatus === 'ready' ? 'TimesFM 3 forecast — calibrated quantiles' : calibrationStatus === 'unavailable' ? 'TimesFM 3 forecast — calibration unavailable' : 'TimesFM 3 forecast — native quantiles'; setForecast({ status: statusLabel, generatedAt: result.generated_at || new Date().toISOString(), count: candles.length, uncertainty: state }); };
        publishForecast(calibrationState);
        if (bars.length >= 106) {
          const thresholdReached = calibrationStatusRef.current === 'ready' && bars.length - calibrationHistoryBars.current >= 16;
          const needsCalibration = !calibrationRunId.current || calibrationStatusRef.current === 'unavailable' || calibrationStatusRef.current === 'not-run' || thresholdReached || (!backendReady && calibrationStatusRef.current === 'ready');
          if (needsCalibration) {
            calibrationAbort.current?.abort(); const calibrationController = new AbortController(); calibrationAbort.current = calibrationController; const calibrationTransition = transitionId;
            startTimesFMCalibration({ symbol, exchange, interval, bars, futureTimestamps, requestId: compactRequestId, signal: calibrationController.signal }).then((started) => {
              if (calibrationTransition !== transition.current || calibrationController.signal.aborted || createdWidget.isDestroyed) return;
              calibrationContextKey.current = started.stable_context_key || started.context_key || calibrationContextKey.current; calibrationRunId.current = started.run_id || calibrationRunId.current; calibrationHistoryBars.current = Number(started.history_bars || calibrationHistoryBars.current || bars.length); calibrationStatusRef.current = started.status || 'running';
              const state = { ...result.uncertainty, calibration_status: started.status, calibration_run_id: calibrationRunId.current, calibration_context_key: calibrationContextKey.current, calibration_completed_at: started.completed_at };
              publishForecast(state);
              if (started.status === 'ready') { lastRequestKey.current = ''; pendingHistoryKey.current = ''; void runForecast({ force: true }); return; }
              if (started.status !== 'running' || !calibrationRunId.current) return;
              if (calibrationTimer.current) clearInterval(calibrationTimer.current);
              calibrationTimer.current = setInterval(async () => { try { const status = await requestTimesFMCalibrationStatusByRunId(calibrationRunId.current, calibrationAbort.current?.signal); if (calibrationTransition !== transition.current) return; if (status.status === 'ready') { clearInterval(calibrationTimer.current); calibrationTimer.current = null; calibrationStatusRef.current = 'ready'; calibrationHistoryBars.current = Number(status.history_bars || calibrationHistoryBars.current); lastRequestKey.current = ''; pendingHistoryKey.current = ''; setForecast((previous) => ({ ...previous, status: 'TimesFM 3 forecast — calibrated quantiles', uncertainty: { ...previous.uncertainty, calibration_status: 'ready', calibration_run_id: calibrationRunId.current, calibration_context_key: calibrationContextKey.current, calibration_completed_at: status.completed_at } })); void runForecast({ force: true }); } else if (status.status === 'failed') { clearInterval(calibrationTimer.current); calibrationTimer.current = null; calibrationStatusRef.current = 'unavailable'; publishForecast({ ...calibrationState, calibration_status: 'unavailable' }); } } catch { /* the live native forecast remains usable while status polling retries */ } }, 2000);
            }).catch((calibrationError) => { if (calibrationError?.name !== 'AbortError' && calibrationTransition === transition.current) { calibrationStatusRef.current = 'unavailable'; publishForecast({ ...result.uncertainty, calibration_status: 'unavailable' }); } });
          }
        }
      } catch (caught) { if (caught.name === 'AbortError' || requestId !== generation.current || transitionId !== transition.current) return; setError(caught.message || 'TimesFM forecast unavailable.'); setForecast((previous) => ({ ...previous, status: 'Forecast unavailable' })); } finally { if (requestId === generation.current && lastRequestKey.current !== requestKey) pendingHistoryKey.current = ''; if (forecastAbort.current === controller) forecastAbort.current = null; }
    };
    const offSymbol = createdWidget.on('symbol', ({ symbol, exchange }) => { beginTransition(createdWidget.interval()); callbacks.current.onActiveChange({ symbol, exchange }); }); const offInterval = createdWidget.on('interval', ({ interval }) => { beginTransition(interval); callbacks.current.onActiveChange({ interval }); }); const offData = createdWidget.on('data', () => { void runForecast(); });
    return () => { forecastAbort.current?.abort(); calibrationAbort.current?.abort(); if (calibrationTimer.current) clearInterval(calibrationTimer.current); offSymbol(); offInterval(); offData(); futureSeries.remove(); fulfilledSeries.remove(); Object.values(quantileSeries).forEach((series) => series.remove()); createdWidget.destroy(); if (widget.current === createdWidget) widget.current = null; };
  } catch (caught) { setTimeout(() => setError(caught.message || 'Unable to start the chart.'), 0); } }, []);

  useEffect(() => { if (widget.current && (widget.current.symbol() !== active.symbol || widget.current.exchange() !== active.exchange)) widget.current.setSymbol(active.symbol, active.exchange); }, [active.symbol, active.exchange]); useEffect(() => { if (widget.current && widget.current.interval() !== active.interval) widget.current.setInterval(active.interval); }, [active.interval]); useEffect(() => { if (mode.current === 'rolling-10') fulfilledByTime.current.clear(); }, [forecastMode]); useEffect(() => { const series = quantileSeriesRef.current; const horizon = forecast.uncertainty?.horizon || []; ['P10', 'P25', 'P50', 'P75', 'P90'].forEach((name) => series[name]?.setData(uncertaintyVisible.current ? horizon.map((item) => ({ time: Number(item.timestamp), value: Number(item.quantiles?.[name] ?? item[name.toLowerCase()]) })) : [])); }, [forecast.uncertainty, forecastUncertaintyVisible]);
  const calibrationStatus = forecast.uncertainty?.calibration_status || 'not-run';
  const calibrationText = calibrationStatus === 'running' ? 'Calibration is running in the background; native lines are shown until it completes.' : calibrationStatus === 'ready' ? 'Calibration complete; calibrated lines are now displayed.' : calibrationStatus === 'unavailable' ? 'Calibration is unavailable; native TimesFM lines remain displayed.' : 'Calibration has not started yet.';
  const directionalProbabilities = forecast.uncertainty?.directional_probability || {};
  const firstHorizonProbability = directionalProbabilities['1'];
  const evidenceLabel = (value) => value ? `${value.slice(0, 1).toUpperCase()}${value.slice(1)} evidence` : '';
  const probabilityHeadline = firstHorizonProbability
    ? `Direction: ${firstHorizonProbability.direction === 'up' ? 'Up' : 'Down'} · Calibrated probability: ${Math.round(Number(firstHorizonProbability.calibrated_probability) * 100)}% · H1 · n=${firstHorizonProbability.sample_count} · ${evidenceLabel(firstHorizonProbability.evidence)}`
    : calibrationStatus === 'running'
      ? 'Direction probability is calibrating; native quantiles remain visible.'
      : null;
  return <div className="chart-terminal"><div className="chart-context"><b>{active.symbol}</b><span>{active.exchange}</span><select value={active.interval} onChange={(e) => onActiveChange({ interval: e.target.value })}>{intervals.map((item) => <option key={item}>{item}</option>)}</select></div><div className="forecast-status" role="status"><b>{forecast.status}</b>{forecast.count > 0 && <span>{forecast.count} forward candles</span>}{forecast.generatedAt && <time dateTime={forecast.generatedAt}>Updated {new Date(forecast.generatedAt).toLocaleTimeString()}</time>}<span className={`calibration-indicator calibration-${calibrationStatus}`}>{calibrationText}</span>{probabilityHeadline && <span className="direction-probability-indicator">{probabilityHeadline}</span>}{forecastDiagnosticsVisible && <button type="button" className="diagnostics-toggle" onClick={() => onForecastUncertaintyVisible?.(!forecastUncertaintyVisible)}>{forecastUncertaintyVisible ? 'Hide quantiles' : 'Show quantiles'}</button>}</div>{forecastDiagnosticsVisible && forecast.uncertainty && <div className="forecast-diagnostics"><span>TimesFM 3 forecast — not trading advice.</span><span>Each line is a close-price quantile for the same future candle.</span><div className="quantile-legend">{quantileLegend.map(([name, meaning, color, style]) => <span key={name} title={meaning}><i style={{ backgroundColor: color, borderTop: `2px ${style} ${color}` }} /> <b>{name}</b> {meaning}</span>)}</div><span className="calibration-explanation">{calibrationText}</span>{Object.keys(directionalProbabilities).length > 0 && <div className="direction-probability-panel"><b>Historical directional estimate</b><table><thead><tr><th>Horizon</th><th>Direction</th><th>Estimate</th><th>80% range</th><th>Evidence</th></tr></thead><tbody>{[1, 3, 5, 10].map((horizon) => { const item = directionalProbabilities[String(horizon)]; return item && <tr key={horizon}><td>H{horizon}</td><td>{item.direction === 'up' ? 'Up' : 'Down'}</td><td>{Math.round(Number(item.calibrated_probability) * 100)}%</td><td>{Math.round(Number(item.uncertainty_interval?.low) * 100)}–{Math.round(Number(item.uncertainty_interval?.high) * 100)}%</td><td>n={item.sample_count} · {evidenceLabel(item.evidence)}</td></tr>; })}</tbody></table><small>Historical calibrated estimate only; it is not a guarantee, trading signal, or order input.</small></div>}</div>}{error && <p className="error">{error}</p>}<div ref={host} className="openalgo-host" /></div>;
}
