import { useEffect, useRef, useState } from 'react';
import { createWidget } from '@layr0/chart-engine/widget';
import { ImcMarketDataFeed } from '../../services/imcFeeds';
import { completedBars, loadForecastCalendar, nextForecastTimes } from '../../services/forecastCalendar';
import { requestTimesFMForecast, requestTimesFMCalibrationStatus, startTimesFMCalibration } from '../../services/timesfmForecast';
import { forecastRequestKey, forecastRequestId } from '../../services/forecastIdentity';
import { AUTHORITATIVE_REFRESH_INTERVAL_MS } from '../../services/refreshPolicy';

const intervals = ['1m', '5m', '15m', '1h', '1d', '1w'];
const futureStyle = { title: 'TimesFM forecast', upColor: 'rgba(139, 92, 246, 0.72)', downColor: 'rgba(245, 158, 11, 0.72)', borderUpColor: '#a78bfa', borderDownColor: '#fbbf24', wickUpColor: '#a78bfa', wickDownColor: '#fbbf24', priceLineVisible: false, lastValueVisible: false };
const fulfilledStyle = { title: 'TimesFM fulfilled forecast', upColor: '#a78bfa', downColor: '#fbbf24', borderUpColor: '#a78bfa', borderDownColor: '#fbbf24', wickUpColor: '#a78bfa', wickDownColor: '#fbbf24', bodyVisible: false, priceLineVisible: false, lastValueVisible: false };
const quantileStyles = {
  P10: { color: 'rgba(129, 140, 248, 0.55)', lineWidth: 1, lineStyle: 'dashed', priceLineVisible: false, lastValueVisible: false },
  P25: { color: 'rgba(167, 139, 250, 0.65)', lineWidth: 1, lineStyle: 'dotted', priceLineVisible: false, lastValueVisible: false },
  P50: { color: '#c4b5fd', lineWidth: 2, priceLineVisible: false, lastValueVisible: false },
  P75: { color: 'rgba(251, 191, 36, 0.65)', lineWidth: 1, lineStyle: 'dotted', priceLineVisible: false, lastValueVisible: false },
  P90: { color: 'rgba(251, 191, 36, 0.55)', lineWidth: 1, lineStyle: 'dashed', priceLineVisible: false, lastValueVisible: false },
};
const quantileLegend = [
  ['P10', 'Lowest 10% outcome boundary', 'rgba(129, 140, 248, 0.9)', 'dashed'],
  ['P25', 'Lower-quarter outcome boundary', 'rgba(167, 139, 250, 0.95)', 'dotted'],
  ['P50', 'Median / central forecast', '#c4b5fd', 'solid'],
  ['P75', 'Upper-quarter outcome boundary', 'rgba(251, 191, 36, 0.95)', 'dotted'],
  ['P90', 'Highest 10% outcome boundary', 'rgba(251, 191, 36, 0.9)', 'dashed'],
];

export default function ChartTerminal({ client, active, onActiveChange, theme, forecastMode, forecastDiagnosticsVisible = true, forecastUncertaintyVisible = true, onForecastUncertaintyVisible }) {
  const host = useRef(null); const widget = useRef(null); const mode = useRef(forecastMode); const abort = useRef(null); const forecastByTime = useRef(new Map()); const fulfilledByTime = useRef(new Map()); const generation = useRef(0); const transition = useRef(0); const lastRequestKey = useRef(''); const pendingHistoryKey = useRef(''); const calibrationContextKey = useRef('');
  const initial = useRef({ symbol: active.symbol, exchange: active.exchange, interval: active.interval, theme }); const callbacks = useRef({ client, onActiveChange });
  const [error, setError] = useState(''); const [forecast, setForecast] = useState({ status: 'Waiting for broker history', generatedAt: null, count: 0, uncertainty: null }); const uncertaintyVisible = useRef(forecastUncertaintyVisible); const quantileSeriesRef = useRef({}); const calibrationTimer = useRef(null);
  useEffect(() => { mode.current = forecastMode; }, [forecastMode]); useEffect(() => { uncertaintyVisible.current = forecastUncertaintyVisible; }, [forecastUncertaintyVisible]); useEffect(() => { callbacks.current = { client, onActiveChange }; }, [client, onActiveChange]);

  useEffect(() => { try {
    const feed = new ImcMarketDataFeed(callbacks.current.client);
    const createdWidget = createWidget(host.current, { feed, symbol: initial.current.symbol, exchange: initial.current.exchange, interval: initial.current.interval, intervals, theme: initial.current.theme, persist: false, mobile: 'auto', lookbackBars: 700, loading: { pollIntervalMs: AUTHORITATIVE_REFRESH_INTERVAL_MS }, symbolSearch: async (query) => { const result = await callbacks.current.client.search(query); return (result.data || result.symbols || []).map((item) => ({ symbol: item.symbol, exchange: item.exchange })); }, onOrder: () => document.querySelector('.trading-panel')?.scrollIntoView({ behavior: 'smooth' }) });
    widget.current = createdWidget;
    const futureSeries = createdWidget.chart.addSeries('candlestick', { style: futureStyle }); const fulfilledSeries = createdWidget.chart.addSeries('candlestick', { style: fulfilledStyle }); const quantileSeries = Object.fromEntries(Object.entries(quantileStyles).map(([name, style]) => [name, createdWidget.chart.addSeries('line', { style })])); quantileSeriesRef.current = quantileSeries;
    const setQuantileData = (uncertainty) => { const horizon = uncertainty?.horizon || []; const source = uncertainty?.display_source === 'calibrated' ? 'calibrated' : 'native'; const keys = ['P10', 'P25', 'P50', 'P75', 'P90']; keys.forEach((name) => quantileSeries[name].setData(uncertaintyVisible.current ? horizon.map((item) => ({ time: Number(item.timestamp), value: Number(item.quantiles?.[name] ?? item[name.toLowerCase()]) })) : [])); return source; };
    const clearForecast = (status = 'Waiting for broker history') => { abort.current?.abort(); abort.current = null; if (calibrationTimer.current) clearInterval(calibrationTimer.current); calibrationTimer.current = null; calibrationContextKey.current = ''; pendingHistoryKey.current = ''; futureSeries.setData([]); fulfilledSeries.setData([]); Object.values(quantileSeries).forEach((series) => series.setData([])); forecastByTime.current.clear(); fulfilledByTime.current.clear(); lastRequestKey.current = ''; setForecast({ status, generatedAt: null, count: 0, uncertainty: null }); };
    const beginTransition = (interval) => { transition.current += 1; generation.current += 1; createdWidget.series.setData([]); clearForecast(`Loading ${interval} history`); };
    const runForecast = async () => {
      const transitionId = transition.current; const symbol = createdWidget.symbol(); const exchange = createdWidget.exchange(); const interval = createdWidget.interval(); const bars = completedBars(createdWidget.series.getData(), interval); if (bars.length === 0) { clearForecast(`Loading ${interval} history`); return; }
      for (const actual of bars) { const predicted = forecastByTime.current.get(actual.time); if (predicted) fulfilledByTime.current.set(actual.time, predicted); } if (mode.current === 'rolling-10') fulfilledByTime.current.clear();
      const history = bars.slice(-512).map(({ time, open, high, low, close, volume }) => ({ time, open, high, low, close, volume })); const pendingKey = JSON.stringify({ symbol, exchange, interval, history }); if (pendingHistoryKey.current === pendingKey) return; pendingHistoryKey.current = pendingKey;
      setForecast((previous) => ({ ...previous, status: `Forecasting ${interval} with TimesFM…` })); setError('');
      let requestKey; const requestId = ++generation.current; const controller = new AbortController(); abort.current?.abort(); abort.current = controller;
      try {
        const calendar = await loadForecastCalendar(callbacks.current.client, history.at(-1).time, exchange, { signal: controller.signal }); if (controller.signal.aborted || transitionId !== transition.current || requestId !== generation.current) return;
        const futureTimestamps = nextForecastTimes({ lastTime: history.at(-1).time, interval, ...calendar }); requestKey = forecastRequestKey({ symbol, exchange, interval, bars: history, futureTimestamps }); const compactRequestId = forecastRequestId(requestKey); if (lastRequestKey.current === requestKey && forecastByTime.current.size === 10) return;
        const result = await requestTimesFMForecast({ symbol, exchange, interval, bars: history, futureTimestamps, requestId: compactRequestId, calibrationContextKey: calibrationContextKey.current || undefined, signal: controller.signal }); if (requestId !== generation.current || transitionId !== transition.current || controller.signal.aborted || createdWidget.isDestroyed) return;
        const candles = result.candles.map((candle) => ({ time: Number(candle.time), open: Number(candle.open), high: Number(candle.high), low: Number(candle.low), close: Number(candle.close), volume: Number(candle.volume || 0) })); forecastByTime.current = new Map(candles.map((candle) => [candle.time, candle])); futureSeries.setData(candles); setQuantileData(result.uncertainty); fulfilledSeries.setData(mode.current === 'retain-fulfilled-overlays' ? [...fulfilledByTime.current.values()] : []); lastRequestKey.current = requestKey;
        let calibrationState = bars.length < 106 ? { ...result.uncertainty, calibration_status: 'unavailable' } : { ...result.uncertainty, calibration_status: 'running' };
        const publishForecast = (state) => { const calibrationStatus = state.calibration_status; const statusLabel = calibrationStatus === 'running' ? 'TimesFM 3 forecast — calibration running' : calibrationStatus === 'ready' ? 'TimesFM 3 forecast — calibrated quantiles' : calibrationStatus === 'unavailable' ? 'TimesFM 3 forecast — calibration unavailable' : 'TimesFM 3 forecast — native quantiles'; setForecast({ status: statusLabel, generatedAt: result.generated_at || new Date().toISOString(), count: candles.length, uncertainty: state }); };
        publishForecast(calibrationState);
        if (bars.length >= 106 && !calibrationContextKey.current) {
          startTimesFMCalibration({ symbol, exchange, interval, bars, futureTimestamps, requestId: compactRequestId, signal: controller.signal }).then((started) => {
            if (requestId !== generation.current || transitionId !== transition.current || controller.signal.aborted) return;
            calibrationContextKey.current = started.context_key || '';
            calibrationState = { ...result.uncertainty, calibration_status: started.status, calibration_run_id: started.run_id, calibration_context_key: started.context_key };
            publishForecast(calibrationState);
            if (calibrationState.calibration_status === 'ready') { lastRequestKey.current = ''; pendingHistoryKey.current = ''; void runForecast(); return; }
            if (calibrationState.calibration_status !== 'running' || !calibrationState.calibration_context_key) return;
            if (calibrationTimer.current) clearInterval(calibrationTimer.current);
            calibrationTimer.current = setInterval(async () => { try { const status = await requestTimesFMCalibrationStatus(calibrationState.calibration_context_key, controller.signal); if (status.status === 'ready') { clearInterval(calibrationTimer.current); calibrationTimer.current = null; lastRequestKey.current = ''; pendingHistoryKey.current = ''; void runForecast(); } else if (status.status === 'failed') { clearInterval(calibrationTimer.current); calibrationTimer.current = null; publishForecast({ ...calibrationState, calibration_status: 'unavailable' }); } } catch { /* forecast remains usable while calibration status is unavailable */ } }, 2000);
          }).catch((calibrationError) => { if (calibrationError?.name !== 'AbortError' && requestId === generation.current && transitionId === transition.current) publishForecast({ ...result.uncertainty, calibration_status: 'unavailable' }); });
        }
      } catch (caught) { if (caught.name === 'AbortError' || requestId !== generation.current || transitionId !== transition.current) return; setError(caught.message || 'TimesFM forecast unavailable.'); setForecast((previous) => ({ ...previous, status: 'Forecast unavailable' })); } finally { if (requestId === generation.current && lastRequestKey.current !== requestKey) pendingHistoryKey.current = ''; if (abort.current === controller) abort.current = null; }
    };
    const offSymbol = createdWidget.on('symbol', ({ symbol, exchange }) => { beginTransition(createdWidget.interval()); callbacks.current.onActiveChange({ symbol, exchange }); }); const offInterval = createdWidget.on('interval', ({ interval }) => { beginTransition(interval); callbacks.current.onActiveChange({ interval }); }); const offData = createdWidget.on('data', () => { void runForecast(); });
    return () => { abort.current?.abort(); if (calibrationTimer.current) clearInterval(calibrationTimer.current); offSymbol(); offInterval(); offData(); futureSeries.remove(); fulfilledSeries.remove(); Object.values(quantileSeries).forEach((series) => series.remove()); createdWidget.destroy(); if (widget.current === createdWidget) widget.current = null; };
  } catch (caught) { setTimeout(() => setError(caught.message || 'Unable to start the chart.'), 0); } }, []);

  useEffect(() => { if (widget.current && (widget.current.symbol() !== active.symbol || widget.current.exchange() !== active.exchange)) widget.current.setSymbol(active.symbol, active.exchange); }, [active.symbol, active.exchange]); useEffect(() => { if (widget.current && widget.current.interval() !== active.interval) widget.current.setInterval(active.interval); }, [active.interval]); useEffect(() => { if (mode.current === 'rolling-10') fulfilledByTime.current.clear(); }, [forecastMode]); useEffect(() => { const series = quantileSeriesRef.current; const horizon = forecast.uncertainty?.horizon || []; ['P10', 'P25', 'P50', 'P75', 'P90'].forEach((name) => series[name]?.setData(uncertaintyVisible.current ? horizon.map((item) => ({ time: Number(item.timestamp), value: Number(item.quantiles?.[name] ?? item[name.toLowerCase()]) })) : [])); }, [forecast.uncertainty, forecastUncertaintyVisible]);
  const calibrationStatus = forecast.uncertainty?.calibration_status || 'not-run';
  const calibrationText = calibrationStatus === 'running' ? 'Calibration is running in the background; native lines are shown until it completes.' : calibrationStatus === 'ready' ? 'Calibration complete; calibrated lines are now displayed.' : calibrationStatus === 'unavailable' ? 'Calibration is unavailable; native TimesFM lines remain displayed.' : 'Calibration has not started yet.';
  return <div className="chart-terminal"><div className="chart-context"><b>{active.symbol}</b><span>{active.exchange}</span><select value={active.interval} onChange={(e) => onActiveChange({ interval: e.target.value })}>{intervals.map((item) => <option key={item}>{item}</option>)}</select></div><div className="forecast-status" role="status"><b>{forecast.status}</b>{forecast.count > 0 && <span>{forecast.count} forward candles</span>}{forecast.generatedAt && <time dateTime={forecast.generatedAt}>Updated {new Date(forecast.generatedAt).toLocaleTimeString()}</time>}<span className={`calibration-indicator calibration-${calibrationStatus}`}>{calibrationText}</span>{forecastDiagnosticsVisible && <button type="button" className="diagnostics-toggle" onClick={() => onForecastUncertaintyVisible?.(!forecastUncertaintyVisible)}>{forecastUncertaintyVisible ? 'Hide quantiles' : 'Show quantiles'}</button>}</div>{forecastDiagnosticsVisible && forecast.uncertainty && <div className="forecast-diagnostics"><span>TimesFM 3 forecast — not trading advice.</span><span>Each line is a close-price quantile for the same future candle.</span><div className="quantile-legend">{quantileLegend.map(([name, meaning, color, style]) => <span key={name} title={meaning}><i style={{ backgroundColor: color, borderTop: `2px ${style} ${color}` }} /> <b>{name}</b> {meaning}</span>)}</div><span className="calibration-explanation">{calibrationText}</span></div>}{error && <p className="error">{error}</p>}<div ref={host} className="openalgo-host" /></div>;
}
