import { useCallback, useEffect, useState } from 'react';
const exchangeFor = (exchange) => exchange === 'BFO' || exchange === 'BSE_INDEX' ? 'BFO' : 'NFO';
export default function OptionChainPanel({ client, active, onSelect }) {
  const [underlying, setUnderlying] = useState('NIFTY'); const [expiry, setExpiry] = useState(''); const [expiries, setExpiries] = useState([]); const [chain, setChain] = useState(null); const [error, setError] = useState(''); const exchange = exchangeFor(active.exchange);
  useEffect(() => { let live = true; client.expiry(underlying, exchange).then((result) => { const values = result.expiries || result.data || []; if (live) { setExpiries(values); setExpiry(values[0]?.expiry_date || values[0] || ''); } }).catch((caught) => live && setError(caught.message)); return () => { live = false; }; }, [client, underlying, exchange]);
  const refresh = useCallback(async () => { if (!expiry) return; try { setError(''); setChain(await client.optionChain(underlying, exchange, expiry)); } catch (caught) { setError(caught.message); } }, [client, underlying, exchange, expiry]);
  useEffect(() => { const initial = setTimeout(refresh, 0); const id = setInterval(refresh, 30000); return () => { clearTimeout(initial); clearInterval(id); }; }, [refresh]);
  const rows = chain?.chain || chain?.data?.chain || [];
  return <section className="side-card option-chain"><header><b>Option chain</b><button onClick={refresh} title="Refresh option chain">↻</button></header><div className="form-row"><select value={underlying} onChange={(e) => setUnderlying(e.target.value)}>{['NIFTY', 'BANKNIFTY', 'FINNIFTY', 'SENSEX'].map((item) => <option key={item}>{item}</option>)}</select><select value={expiry} onChange={(e) => setExpiry(e.target.value)}>{expiries.map((item) => { const value = item.expiry_date || item; return <option key={value} value={value}>{value}</option>; })}</select></div>{error && <p className="error">{error}</p>}<div className="chain-spot">Spot {Number(chain?.underlying_ltp ?? chain?.underlyingLTP ?? chain?.ltp ?? 0).toFixed(2)} · ATM {chain?.atm_strike ?? chain?.atmStrike ?? '—'}</div><div className="chain-table"><div className="chain-head"><span>CE</span><span>Strike</span><span>PE</span></div>{rows.map((row) => <div className="chain-row" key={row.strike}><button disabled={!row.ce} onClick={() => onSelect({ ...row.ce, exchange })}>{row.ce?.ltp ?? '—'}<small>{row.ce?.oi ?? ''}</small></button><b className={String(row.strike) === String(chain?.atm_strike ?? chain?.atmStrike) ? 'atm' : ''}>{row.strike}</b><button disabled={!row.pe} onClick={() => onSelect({ ...row.pe, exchange })}>{row.pe?.ltp ?? '—'}<small>{row.pe?.oi ?? ''}</small></button></div>)}</div></section>;
}
