import { useCallback, useEffect, useState } from 'react';
const initialOrder = { action: 'BUY', quantity: 1, product: 'MIS', pricetype: 'MARKET', price: '' };
export default function TradingPanel({ client, active }) {
  const [mode, setMode] = useState(null); const [order, setOrder] = useState(initialOrder); const [status, setStatus] = useState(''); const [busy, setBusy] = useState(false);
  const refreshMode = useCallback(() => client.analyzer().then(setMode).catch((error) => setStatus(error.message)), [client]);
  useEffect(() => { void refreshMode(); }, [refreshMode]);
  const submit = async (event) => { event.preventDefault(); setBusy(true); setStatus(''); try { const result = await client.placeOrder({ symbol: active.symbol, exchange: active.exchange, ...order, quantity: Number(order.quantity), price: order.price ? Number(order.price) : undefined, expected_mode: mode?.mode || mode?.analyzer_mode, mode_version: mode?.version }); setStatus(`Order accepted: ${result.orderid || result.order_id || 'submitted'}`); } catch (error) { setStatus(error.message); } finally { setBusy(false); } };
  return <section className="side-card trading-card"><header><b>Order ticket</b><button onClick={refreshMode}>↻</button></header><div className={`mode-pill ${mode?.mode === 'live' ? 'live' : 'analyzer'}`}>{mode?.mode || mode?.analyzer_mode || 'Mode unavailable'}</div><p className="instrument">{active.symbol} · {active.exchange}</p><form onSubmit={submit}><div className="form-row"><select value={order.action} onChange={(e) => setOrder({ ...order, action: e.target.value })}><option>BUY</option><option>SELL</option></select><input aria-label="Quantity" min="1" type="number" value={order.quantity} onChange={(e) => setOrder({ ...order, quantity: e.target.value })} /></div><div className="form-row"><select value={order.product} onChange={(e) => setOrder({ ...order, product: e.target.value })}><option>MIS</option><option>CNC</option><option>NRML</option></select><select value={order.pricetype} onChange={(e) => setOrder({ ...order, pricetype: e.target.value })}><option>MARKET</option><option>LIMIT</option><option>SL</option><option>SL-M</option></select></div>{order.pricetype !== 'MARKET' && <input aria-label="Price" placeholder="Limit price" type="number" value={order.price} onChange={(e) => setOrder({ ...order, price: e.target.value })} />}<button className={`place-order ${order.action === 'BUY' ? 'buy' : 'sell'}`} disabled={busy || !mode}>{busy ? 'Submitting…' : `${order.action} ${active.symbol}`}</button></form>{status && <p className="trade-status">{status}</p>}<p className="safety-note">IMC validates the current analyzer/live mode when the order is submitted.</p></section>;
}
